name: Deploy Demo Site

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
    paths:
      - "dark.css"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Directories
        run: |
          mkdir ./gh-pages ./master
          
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "./gh-pages"
          
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: "./master"
      
      - name: Copy dark.css
        run: |
          yes | cp -rfv ./master/dark.css ./gh-pages/css/dark.css
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
